name: nightly
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          file: stable/buster/Dockerfile
          push: true
          tags:
            - ghcr.io/flavorjones/docker-truffleruby:nightly
      - run: echo ${{ steps.docker_build.outputs.digest }}
